language: python
python:
    - "3.8"
before_script:
  - pip install --upgrade tox setuptools virtualenv wheel
install:
  - pip install --user -r test-requirements.txt
  - pip install --user -r requirements.txt

script: tox
notifications:
  on_success: change
  on_failuer: always

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
