# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.9.2'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.2'
  displayName: 'Use Python 3.9.2'

- script: |
    python -m pip install tox
    python -m pip install flake8
  displayName: 'Install tox and flake8'

- script: |
    python -m unittest discover -s tests -p "*_test.py" -v
  displayName: 'Unit tests'

- script: |
    flake8 pyinels tests
  displayName: 'Linting with flake8'